#!/bin/sh
set -eu
# Verification never opens local or production traffic; it emits closed evidence only.
: "${TRAFFIC_OPEN_MARKER_FILE:?Set TRAFFIC_OPEN_MARKER_FILE}"
: "${RESTORE_EVIDENCE_FILE:?Set RESTORE_EVIDENCE_FILE}"
: "${B2B3_EVIDENCE_FILE:?Set B2B3_EVIDENCE_FILE}"
: "${B2B3_EVIDENCE_SIGNATURE_FILE:?Set B2B3_EVIDENCE_SIGNATURE_FILE}"
: "${B2B3_EVIDENCE_VERIFY_KEY_FILE:?Set B2B3_EVIDENCE_VERIFY_KEY_FILE}"
: "${DRILL_EVIDENCE_FILE:?Set DRILL_EVIDENCE_FILE}"
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec python3 "$SCRIPT_DIR/backupctl.py" traffic-gate \
  "$RESTORE_EVIDENCE_FILE" \
  "$B2B3_EVIDENCE_FILE" \
  "$B2B3_EVIDENCE_SIGNATURE_FILE" \
  "$B2B3_EVIDENCE_VERIFY_KEY_FILE" \
  "$TRAFFIC_OPEN_MARKER_FILE" \
  "$DRILL_EVIDENCE_FILE"
