"""screening persistence foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0006_screening_foundation"; down_revision="0005_durable_queue"; branch_labels=None; depends_on=None

def common(): return [sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())]
def upgrade():
    op.create_unique_constraint("uq_job_jd_versions_tenant_id","job_jd_versions",["organization_id","id"]); op.create_unique_constraint("uq_job_jd_versions_tenant_job_id","job_jd_versions",["organization_id","job_id","id"])
    op.create_unique_constraint("uq_screening_rule_versions_tenant_id","screening_rule_versions",["organization_id","id"]); op.create_unique_constraint("uq_screening_rule_versions_tenant_job_id","screening_rule_versions",["organization_id","job_id","id"])
    op.create_table("screening_runs",*common(),sa.Column("job_id",sa.Uuid(),nullable=False),sa.Column("jd_version_id",sa.Uuid(),nullable=False),sa.Column("rule_version_id",sa.Uuid(),nullable=False),sa.Column("source",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="queued"),sa.Column("total_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("processed_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("succeeded_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("failed_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("created_by",sa.Uuid(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("organization_id","id"),sa.ForeignKeyConstraint(["organization_id","job_id"],["jobs.organization_id","jobs.id"]),sa.ForeignKeyConstraint(["organization_id","job_id","jd_version_id"],["job_jd_versions.organization_id","job_jd_versions.job_id","job_jd_versions.id"]),sa.ForeignKeyConstraint(["organization_id","job_id","rule_version_id"],["screening_rule_versions.organization_id","screening_rule_versions.job_id","screening_rule_versions.id"]),sa.ForeignKeyConstraint(["organization_id","created_by"],["users.organization_id","users.id"]),sa.CheckConstraint("source in ('upload','manual')",name="ck_screening_runs_source"),sa.CheckConstraint("status in ('queued','parsing','rule_scoring','llm_scoring','completed','partial','failed','cancelled')",name="ck_screening_runs_status"),sa.CheckConstraint("version>=1",name="ck_screening_runs_version"),sa.CheckConstraint("total_count>=0 AND processed_count>=0 AND succeeded_count>=0 AND failed_count>=0 AND processed_count=succeeded_count+failed_count AND processed_count<=total_count",name="ck_screening_runs_counts"))
    op.create_index("ix_screening_runs_status","screening_runs",["organization_id","status","created_at"])
    op.create_table("screening_items",*common(),sa.Column("run_id",sa.Uuid(),nullable=False),sa.Column("file_object_id",sa.Uuid(),nullable=False),sa.Column("candidate_id",sa.Uuid()),sa.Column("resume_id",sa.Uuid()),sa.Column("application_id",sa.Uuid()),sa.Column("status",sa.String(32),nullable=False,server_default="queued"),sa.Column("parser_version",sa.String(64)),sa.Column("parse_quality",sa.String(32)),sa.Column("safe_error_code",sa.String(64)),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("organization_id","id"),sa.UniqueConstraint("organization_id","run_id","file_object_id"),sa.ForeignKeyConstraint(["organization_id","run_id"],["screening_runs.organization_id","screening_runs.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id","file_object_id"],["file_objects.organization_id","file_objects.id"]),sa.ForeignKeyConstraint(["organization_id","candidate_id"],["candidates.organization_id","candidates.id"]),sa.ForeignKeyConstraint(["organization_id","resume_id"],["resumes.organization_id","resumes.id"]),sa.ForeignKeyConstraint(["organization_id","application_id"],["applications.organization_id","applications.id"]),sa.CheckConstraint("status in ('queued','parsing','parsed','scoring','scored','failed','cancelled')",name="ck_screening_items_status"),sa.CheckConstraint("attempts>=0",name="ck_screening_items_attempts"))
    op.create_index("ix_screening_items_progress","screening_items",["organization_id","run_id","status","created_at"]); op.create_index("ix_screening_items_failures","screening_items",["organization_id","status","safe_error_code"])
    op.create_table("screening_results",*common(),sa.Column("item_id",sa.Uuid(),nullable=False),sa.Column("application_id",sa.Uuid()),sa.Column("resume_id",sa.Uuid()),sa.Column("rule_engine_version",sa.String(64),nullable=False),sa.Column("rule_score",sa.Integer(),nullable=False),sa.Column("recommendation",sa.String(32),nullable=False),sa.Column("required_hits",postgresql.JSONB(),nullable=False),sa.Column("required_missing",postgresql.JSONB(),nullable=False),sa.Column("bonus_hits",postgresql.JSONB(),nullable=False),sa.Column("estimated_years",sa.Integer(),nullable=False),sa.Column("risks",postgresql.JSONB(),nullable=False),sa.Column("questions",postgresql.JSONB(),nullable=False),sa.Column("human_override_recommendation",sa.String(32)),sa.Column("human_override_reason_code",sa.String(64)),sa.Column("human_override_by",sa.Uuid()),sa.Column("human_override_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("organization_id","item_id","rule_engine_version"),sa.ForeignKeyConstraint(["organization_id","item_id"],["screening_items.organization_id","screening_items.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id","application_id"],["applications.organization_id","applications.id"]),sa.ForeignKeyConstraint(["organization_id","resume_id"],["resumes.organization_id","resumes.id"]),sa.ForeignKeyConstraint(["organization_id","human_override_by"],["users.organization_id","users.id"]),sa.CheckConstraint("rule_score between 0 and 100",name="ck_screening_results_score"),sa.CheckConstraint("estimated_years>=0",name="ck_screening_results_years"),sa.CheckConstraint("recommendation in ('优先沟通','可沟通','暂缓','需人工复核')",name="ck_screening_results_recommendation"),sa.CheckConstraint("human_override_recommendation is null or human_override_recommendation in ('优先沟通','可沟通','暂缓','需人工复核')",name="ck_screening_results_override_recommendation"),sa.CheckConstraint("(human_override_recommendation is null and human_override_reason_code is null and human_override_by is null and human_override_at is null) or (human_override_recommendation is not null and human_override_reason_code is not null and human_override_by is not null and human_override_at is not null)",name="ck_screening_results_override_complete"))
    op.create_table("candidate_duplicate_hints",*common(),sa.Column("left_candidate_id",sa.Uuid()),sa.Column("right_candidate_id",sa.Uuid()),sa.Column("file_object_id",sa.Uuid()),sa.Column("candidate_id",sa.Uuid()),sa.Column("signals",postgresql.JSONB(),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="pending"),sa.ForeignKeyConstraint(["organization_id","left_candidate_id"],["candidates.organization_id","candidates.id"]),sa.ForeignKeyConstraint(["organization_id","right_candidate_id"],["candidates.organization_id","candidates.id"]),sa.ForeignKeyConstraint(["organization_id","file_object_id"],["file_objects.organization_id","file_objects.id"]),sa.ForeignKeyConstraint(["organization_id","candidate_id"],["candidates.organization_id","candidates.id"]),sa.CheckConstraint("status in ('pending','dismissed','confirmed')",name="ck_duplicate_hints_status"),sa.CheckConstraint("(left_candidate_id is not null AND right_candidate_id is not null) OR file_object_id is not null",name="ck_duplicate_hints_signal")); op.create_index("ix_duplicate_hints_lookup","candidate_duplicate_hints",["organization_id","status","candidate_id","file_object_id"])
    op.execute("""CREATE FUNCTION protect_screening_run_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.job_id<>OLD.job_id OR NEW.jd_version_id<>OLD.jd_version_id OR NEW.rule_version_id<>OLD.rule_version_id OR NEW.source<>OLD.source OR NEW.created_by<>OLD.created_by OR NEW.created_at<>OLD.created_at THEN RAISE EXCEPTION 'screening snapshot is immutable' USING ERRCODE='55000'; END IF; RETURN NEW; END $$"""); op.execute("CREATE TRIGGER screening_run_snapshot_immutable BEFORE UPDATE ON screening_runs FOR EACH ROW EXECUTE FUNCTION protect_screening_run_snapshot()")
    op.execute("""CREATE FUNCTION protect_screening_result() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' OR NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.item_id<>OLD.item_id OR NEW.application_id IS DISTINCT FROM OLD.application_id OR NEW.resume_id IS DISTINCT FROM OLD.resume_id OR NEW.rule_engine_version<>OLD.rule_engine_version OR NEW.rule_score<>OLD.rule_score OR NEW.recommendation<>OLD.recommendation OR NEW.required_hits<>OLD.required_hits OR NEW.required_missing<>OLD.required_missing OR NEW.bonus_hits<>OLD.bonus_hits OR NEW.estimated_years<>OLD.estimated_years OR NEW.risks<>OLD.risks OR NEW.questions<>OLD.questions OR NEW.created_at<>OLD.created_at THEN RAISE EXCEPTION 'screening result facts are append-only' USING ERRCODE='55000'; END IF; RETURN NEW; END $$"""); op.execute("CREATE TRIGGER screening_result_immutable BEFORE UPDATE OR DELETE ON screening_results FOR EACH ROW EXECUTE FUNCTION protect_screening_result()")
def downgrade():
    op.drop_table("candidate_duplicate_hints"); op.drop_table("screening_results"); op.execute("DROP FUNCTION protect_screening_result()"); op.drop_table("screening_items"); op.drop_table("screening_runs"); op.execute("DROP FUNCTION protect_screening_run_snapshot()"); op.drop_constraint("uq_screening_rule_versions_tenant_job_id","screening_rule_versions",type_="unique"); op.drop_constraint("uq_screening_rule_versions_tenant_id","screening_rule_versions",type_="unique"); op.drop_constraint("uq_job_jd_versions_tenant_job_id","job_jd_versions",type_="unique"); op.drop_constraint("uq_job_jd_versions_tenant_id","job_jd_versions",type_="unique")
