"""LLM provider configuration foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0009_llm_gateway_foundation"; down_revision="0008_screening_cleanup_marker"; branch_labels=None; depends_on=None
def upgrade():
    op.create_unique_constraint("uq_screening_results_tenant_id","screening_results",["organization_id","id"])
    op.create_table("llm_provider_configs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("provider_id",sa.String(64),nullable=False),sa.Column("model",sa.String(128),nullable=False),sa.Column("encrypted_api_key",sa.LargeBinary()),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("allowed_job_ids",postgresql.JSONB(),nullable=False,server_default="[]"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_by",sa.Uuid(),nullable=False),sa.Column("updated_by",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("last_test_status",sa.String(20)),sa.Column("last_test_error_code",sa.String(64)),sa.Column("last_test_latency_ms",sa.Integer()),sa.Column("last_tested_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("organization_id"),sa.UniqueConstraint("organization_id","id"),sa.ForeignKeyConstraint(["organization_id","created_by"],["users.organization_id","users.id"]),sa.ForeignKeyConstraint(["organization_id","updated_by"],["users.organization_id","users.id"]),sa.CheckConstraint("version>=1",name="ck_llm_provider_configs_version"),sa.CheckConstraint("not enabled or encrypted_api_key is not null",name="ck_llm_provider_configs_enabled_key"),sa.CheckConstraint("last_test_status is null or last_test_status in ('succeeded','failed')",name="ck_llm_provider_configs_test_status"),sa.CheckConstraint("last_test_latency_ms is null or last_test_latency_ms>=0",name="ck_llm_provider_configs_latency"))
    op.create_table("prompt_versions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("content",postgresql.JSONB(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_by",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("organization_id","id"),sa.UniqueConstraint("organization_id","name","version_number"),sa.ForeignKeyConstraint(["organization_id","created_by"],["users.organization_id","users.id"]),sa.CheckConstraint("version_number>=1",name="ck_prompt_versions_number"))
    op.create_table("llm_invocations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("config_id",sa.Uuid(),nullable=False),sa.Column("prompt_version_id",sa.Uuid()),sa.Column("screening_result_id",sa.Uuid()),sa.Column("provider_id",sa.String(64),nullable=False),sa.Column("model",sa.String(128),nullable=False),sa.Column("request_field_manifest",postgresql.JSONB(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("latency_ms",sa.Integer()),sa.Column("usage",postgresql.JSONB(),nullable=False,server_default="{}"),sa.Column("safe_error_code",sa.String(64)),sa.Column("trace_id",sa.String(100)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.ForeignKeyConstraint(["organization_id","config_id"],["llm_provider_configs.organization_id","llm_provider_configs.id"]),sa.ForeignKeyConstraint(["organization_id","prompt_version_id"],["prompt_versions.organization_id","prompt_versions.id"]),sa.ForeignKeyConstraint(["organization_id","screening_result_id"],["screening_results.organization_id","screening_results.id"]),sa.CheckConstraint("status in ('queued','succeeded','failed')",name="ck_llm_invocations_status"),sa.CheckConstraint("latency_ms is null or latency_ms>=0",name="ck_llm_invocations_latency"))
    op.execute("""CREATE FUNCTION protect_prompt_version() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'prompt versions are append-only' USING ERRCODE='55000'; END $$"""); op.execute("CREATE TRIGGER prompt_versions_append_only BEFORE UPDATE OR DELETE ON prompt_versions FOR EACH ROW EXECUTE FUNCTION protect_prompt_version()")
    op.execute("""CREATE FUNCTION protect_llm_invocation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'LLM invocations are append-only' USING ERRCODE='55000'; END $$"""); op.execute("CREATE TRIGGER llm_invocations_append_only BEFORE UPDATE OR DELETE ON llm_invocations FOR EACH ROW EXECUTE FUNCTION protect_llm_invocation()")
def downgrade():
    op.drop_table("llm_invocations"); op.execute("DROP FUNCTION protect_llm_invocation()"); op.drop_table("prompt_versions"); op.execute("DROP FUNCTION protect_prompt_version()"); op.drop_table("llm_provider_configs"); op.drop_constraint("uq_screening_results_tenant_id","screening_results",type_="unique")
