"""LLM screening evaluation persistence foundation."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="0010_llm_screening_evaluations"; down_revision="0009_llm_gateway_foundation"; branch_labels=None; depends_on=None

def upgrade():
    op.add_column("screening_items",sa.Column("llm_status",sa.String(32),nullable=False,server_default="not_requested")); op.add_column("screening_items",sa.Column("llm_safe_error_code",sa.String(64))); op.add_column("screening_items",sa.Column("llm_attempts",sa.Integer(),nullable=False,server_default="0")); op.add_column("screening_items",sa.Column("llm_started_at",sa.DateTime(timezone=True))); op.add_column("screening_items",sa.Column("llm_finished_at",sa.DateTime(timezone=True)))
    op.create_check_constraint("ck_screening_items_llm_status","screening_items","llm_status in ('not_requested','queued','running','succeeded','failed','skipped')"); op.create_check_constraint("ck_screening_items_llm_attempts","screening_items","llm_attempts>=0")
    op.add_column("llm_invocations",sa.Column("queue_job_id",sa.Uuid())); op.add_column("llm_invocations",sa.Column("attempt_no",sa.Integer())); op.add_column("llm_invocations",sa.Column("config_version",sa.Integer())); op.add_column("llm_invocations",sa.Column("input_sha256",sa.String(64)))
    op.create_unique_constraint("uq_llm_invocations_tenant_id","llm_invocations",["organization_id","id"]); op.create_unique_constraint("uq_llm_invocations_evaluation_link","llm_invocations",["organization_id","id","screening_result_id","prompt_version_id"]); op.create_unique_constraint("uq_llm_invocations_queue_attempt","llm_invocations",["organization_id","queue_job_id","attempt_no"])
    op.create_foreign_key("fk_llm_invocations_queue_job_same_org","llm_invocations","background_jobs",["organization_id","queue_job_id"],["organization_id","id"])
    op.create_check_constraint("ck_llm_invocations_orchestration_complete","llm_invocations","(queue_job_id is null and attempt_no is null and config_version is null and input_sha256 is null) or (queue_job_id is not null and attempt_no is not null and config_version is not null and input_sha256 is not null)"); op.create_check_constraint("ck_llm_invocations_attempt_no","llm_invocations","attempt_no is null or attempt_no>=1"); op.create_check_constraint("ck_llm_invocations_config_version","llm_invocations","config_version is null or config_version>=1"); op.create_check_constraint("ck_llm_invocations_input_sha256","llm_invocations","input_sha256 is null or length(input_sha256)=64")
    op.create_table("llm_screening_evaluations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("screening_result_id",sa.Uuid(),nullable=False),sa.Column("invocation_id",sa.Uuid(),nullable=False),sa.Column("prompt_version_id",sa.Uuid(),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("recommendation",sa.String(32),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("strengths",postgresql.JSONB(),nullable=False),sa.Column("gaps",postgresql.JSONB(),nullable=False),sa.Column("risks",postgresql.JSONB(),nullable=False),sa.Column("interview_questions",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("organization_id","id"),sa.UniqueConstraint("organization_id","invocation_id"),sa.ForeignKeyConstraint(["organization_id","screening_result_id"],["screening_results.organization_id","screening_results.id"]),sa.ForeignKeyConstraint(["organization_id","prompt_version_id"],["prompt_versions.organization_id","prompt_versions.id"]),sa.ForeignKeyConstraint(["organization_id","invocation_id","screening_result_id","prompt_version_id"],["llm_invocations.organization_id","llm_invocations.id","llm_invocations.screening_result_id","llm_invocations.prompt_version_id"]),sa.CheckConstraint("score between 0 and 100",name="ck_llm_screening_evaluations_score"),sa.CheckConstraint("recommendation in ('优先沟通','可沟通','暂缓','需人工复核')",name="ck_llm_screening_evaluations_recommendation"))
    op.execute("""CREATE FUNCTION protect_llm_screening_evaluation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'LLM screening evaluations are append-only' USING ERRCODE='55000'; END $$"""); op.execute("CREATE TRIGGER llm_screening_evaluations_append_only BEFORE UPDATE OR DELETE ON llm_screening_evaluations FOR EACH ROW EXECUTE FUNCTION protect_llm_screening_evaluation()")

def downgrade():
    op.drop_table("llm_screening_evaluations"); op.execute("DROP FUNCTION protect_llm_screening_evaluation()")
    op.drop_constraint("ck_llm_invocations_input_sha256","llm_invocations",type_="check"); op.drop_constraint("ck_llm_invocations_config_version","llm_invocations",type_="check"); op.drop_constraint("ck_llm_invocations_attempt_no","llm_invocations",type_="check"); op.drop_constraint("ck_llm_invocations_orchestration_complete","llm_invocations",type_="check"); op.drop_constraint("fk_llm_invocations_queue_job_same_org","llm_invocations",type_="foreignkey"); op.drop_constraint("uq_llm_invocations_queue_attempt","llm_invocations",type_="unique"); op.drop_constraint("uq_llm_invocations_evaluation_link","llm_invocations",type_="unique"); op.drop_constraint("uq_llm_invocations_tenant_id","llm_invocations",type_="unique")
    for column in ("input_sha256","config_version","attempt_no","queue_job_id"): op.drop_column("llm_invocations",column)
    op.drop_constraint("ck_screening_items_llm_attempts","screening_items",type_="check"); op.drop_constraint("ck_screening_items_llm_status","screening_items",type_="check")
    for column in ("llm_finished_at","llm_started_at","llm_attempts","llm_safe_error_code","llm_status"): op.drop_column("screening_items",column)
