import uuid
from datetime import datetime, timezone
from sqlalchemy import JSON, CheckConstraint, DateTime, ForeignKeyConstraint, Index, Integer, String, Text, UniqueConstraint, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from server.app.identity.models import Base
from server.app.recruiting import models as recruiting_models  # noqa: F401

JSON_DOCUMENT = JSON().with_variant(JSONB(), "postgresql")
def now(): return datetime.now(timezone.utc)

class Record:
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    organization_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now)

class ScreeningRun(Record, Base):
    __tablename__="screening_runs"
    job_id: Mapped[uuid.UUID]=mapped_column(Uuid); jd_version_id: Mapped[uuid.UUID]=mapped_column(Uuid); rule_version_id: Mapped[uuid.UUID]=mapped_column(Uuid)
    source: Mapped[str]=mapped_column(String(32)); status: Mapped[str]=mapped_column(String(32),default="queued")
    total_count: Mapped[int]=mapped_column(Integer,default=0); processed_count: Mapped[int]=mapped_column(Integer,default=0); succeeded_count: Mapped[int]=mapped_column(Integer,default=0); failed_count: Mapped[int]=mapped_column(Integer,default=0)
    created_by: Mapped[uuid.UUID]=mapped_column(Uuid); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); version: Mapped[int]=mapped_column(Integer,default=1)
    __table_args__=(UniqueConstraint("organization_id","id"),ForeignKeyConstraint(["organization_id","job_id"],["jobs.organization_id","jobs.id"]),ForeignKeyConstraint(["organization_id","job_id","jd_version_id"],["job_jd_versions.organization_id","job_jd_versions.job_id","job_jd_versions.id"]),ForeignKeyConstraint(["organization_id","job_id","rule_version_id"],["screening_rule_versions.organization_id","screening_rule_versions.job_id","screening_rule_versions.id"]),ForeignKeyConstraint(["organization_id","created_by"],["users.organization_id","users.id"]),CheckConstraint("source in ('upload','manual')",name="ck_screening_runs_source"),CheckConstraint("status in ('queued','parsing','rule_scoring','llm_scoring','completed','partial','failed','cancelled')",name="ck_screening_runs_status"),CheckConstraint("version>=1",name="ck_screening_runs_version"),CheckConstraint("total_count>=0 AND processed_count>=0 AND succeeded_count>=0 AND failed_count>=0 AND processed_count=succeeded_count+failed_count AND processed_count<=total_count",name="ck_screening_runs_counts"),Index("ix_screening_runs_status","organization_id","status","created_at"))

class ScreeningItem(Record, Base):
    __tablename__="screening_items"
    run_id: Mapped[uuid.UUID]=mapped_column(Uuid); file_object_id: Mapped[uuid.UUID]=mapped_column(Uuid); candidate_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); resume_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); application_id: Mapped[uuid.UUID|None]=mapped_column(Uuid)
    status: Mapped[str]=mapped_column(String(32),default="queued"); parser_version: Mapped[str|None]=mapped_column(String(64)); parse_quality: Mapped[str|None]=mapped_column(String(32)); safe_error_code: Mapped[str|None]=mapped_column(String(64)); attempts: Mapped[int]=mapped_column(Integer,default=0); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
    llm_status: Mapped[str]=mapped_column(String(32),default="not_requested"); llm_safe_error_code: Mapped[str|None]=mapped_column(String(64)); llm_attempts: Mapped[int]=mapped_column(Integer,default=0); llm_started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); llm_finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
    __table_args__=(UniqueConstraint("organization_id","id"),UniqueConstraint("organization_id","run_id","file_object_id"),ForeignKeyConstraint(["organization_id","run_id"],["screening_runs.organization_id","screening_runs.id"],ondelete="CASCADE"),ForeignKeyConstraint(["organization_id","file_object_id"],["file_objects.organization_id","file_objects.id"]),ForeignKeyConstraint(["organization_id","candidate_id"],["candidates.organization_id","candidates.id"]),ForeignKeyConstraint(["organization_id","resume_id"],["resumes.organization_id","resumes.id"]),ForeignKeyConstraint(["organization_id","application_id"],["applications.organization_id","applications.id"]),CheckConstraint("status in ('queued','parsing','parsed','scoring','scored','failed','cancelled')",name="ck_screening_items_status"),CheckConstraint("attempts>=0",name="ck_screening_items_attempts"),CheckConstraint("llm_status in ('not_requested','queued','running','succeeded','failed','skipped')",name="ck_screening_items_llm_status"),CheckConstraint("llm_attempts>=0",name="ck_screening_items_llm_attempts"),Index("ix_screening_items_progress","organization_id","run_id","status","created_at"),Index("ix_screening_items_failures","organization_id","status","safe_error_code"))

class ScreeningResult(Record, Base):
    __tablename__="screening_results"
    item_id: Mapped[uuid.UUID]=mapped_column(Uuid); application_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); resume_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); rule_engine_version: Mapped[str]=mapped_column(String(64)); rule_score: Mapped[int]=mapped_column(Integer); recommendation: Mapped[str]=mapped_column(String(32)); required_hits: Mapped[list]=mapped_column(JSON_DOCUMENT); required_missing: Mapped[list]=mapped_column(JSON_DOCUMENT); bonus_hits: Mapped[list]=mapped_column(JSON_DOCUMENT); estimated_years: Mapped[int]=mapped_column(Integer); risks: Mapped[list]=mapped_column(JSON_DOCUMENT); questions: Mapped[list]=mapped_column(JSON_DOCUMENT); human_override_recommendation: Mapped[str|None]=mapped_column(String(32)); human_override_reason_code: Mapped[str|None]=mapped_column(String(64)); human_override_by: Mapped[uuid.UUID|None]=mapped_column(Uuid); human_override_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
    __table_args__=(UniqueConstraint("organization_id","id"),UniqueConstraint("organization_id","item_id","rule_engine_version"),ForeignKeyConstraint(["organization_id","item_id"],["screening_items.organization_id","screening_items.id"],ondelete="CASCADE"),ForeignKeyConstraint(["organization_id","application_id"],["applications.organization_id","applications.id"]),ForeignKeyConstraint(["organization_id","resume_id"],["resumes.organization_id","resumes.id"]),ForeignKeyConstraint(["organization_id","human_override_by"],["users.organization_id","users.id"]),CheckConstraint("rule_score between 0 and 100",name="ck_screening_results_score"),CheckConstraint("estimated_years>=0",name="ck_screening_results_years"),CheckConstraint("recommendation in ('优先沟通','可沟通','暂缓','需人工复核')",name="ck_screening_results_recommendation"),CheckConstraint("human_override_recommendation is null or human_override_recommendation in ('优先沟通','可沟通','暂缓','需人工复核')",name="ck_screening_results_override_recommendation"),CheckConstraint("(human_override_recommendation is null and human_override_reason_code is null and human_override_by is null and human_override_at is null) or (human_override_recommendation is not null and human_override_reason_code is not null and human_override_by is not null and human_override_at is not null)",name="ck_screening_results_override_complete"))

class CandidateDuplicateHint(Record, Base):
    __tablename__="candidate_duplicate_hints"
    left_candidate_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); right_candidate_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); file_object_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); candidate_id: Mapped[uuid.UUID|None]=mapped_column(Uuid); signals: Mapped[dict]=mapped_column(JSON_DOCUMENT); status: Mapped[str]=mapped_column(String(20),default="pending")
    __table_args__=(ForeignKeyConstraint(["organization_id","left_candidate_id"],["candidates.organization_id","candidates.id"]),ForeignKeyConstraint(["organization_id","right_candidate_id"],["candidates.organization_id","candidates.id"]),ForeignKeyConstraint(["organization_id","file_object_id"],["file_objects.organization_id","file_objects.id"]),ForeignKeyConstraint(["organization_id","candidate_id"],["candidates.organization_id","candidates.id"]),CheckConstraint("status in ('pending','dismissed','confirmed')",name="ck_duplicate_hints_status"),CheckConstraint("(left_candidate_id is not null AND right_candidate_id is not null) OR file_object_id is not null",name="ck_duplicate_hints_signal"),Index("ix_duplicate_hints_lookup","organization_id","status","candidate_id","file_object_id"))
